obj-m += driver.o
PWD := $(shell pwd)
CCPREFIX := arm-linux-gnueabihf-

KDIR = /home/rama/linux

all:
	make ARCH=arm CROSS_COMPILE=${CCPREFIX} -C $(KDIR)  M=$(shell pwd) modules

clean:
	make ARCH=arm CROSS_COMPILE=${CCPREFIX} -C $(KDIR)  M=$(shell pwd) clean

